---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: adm
  name: seel
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services/proxy"]
  verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  seel
  namespace: adm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: seel
  namespace: adm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: seel
subjects:
- kind: ServiceAccount
  name: seel
  namespace: adm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seel
  namespace: adm
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.seel: semver:~1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seel
  strategy: {}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: seel
    spec:
      containers:
      - name: seel
        image: sgryczan/seel:0.0.4
        imagePullPolicy: Always
      serviceAccountName: seel
      enableServiceLinks: true
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: adm
  name: seel
spec:
  type: ClusterIP
  selector:
    app: seel
  ports:
  - name: http
    port: 80
    targetPort: 8080
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: seel
  namespace: adm
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
spec:
  tls:
  - hosts:
    - seel.contoso.com
    secretName: wildcard-cert
  rules:
  - host: seel.contoso.com
    http:
      paths:
      - backend:
          serviceName: seel
          servicePort: 80
---
